### PR TITLE
QuarkNet DAQ decoding

### PR DESCRIPTION
**Pull request by tpmccauley**
A few classes and some code to read in the QN data format and to decode into objects

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
@Tontonis, @twhyntie: Would one of you gents be so kind as to check @tpmccauley's code and merge the PR if all looks good? Thank you. :)

**Comment by twhyntie** [comment]
Are we going to insist on not committing to master yet? :wink:

https://guides.github.com/introduction/flow/

**Comment by RaoOfPhysics** [comment]
No harm in merging a PR into master, but ideally you'd work on a named branch (preferably indicating the problem or solution). :) @tpmccauley's going to have to deal with conflicts when he tries to `git pull upstream master`. :D

**Comment by tpmccauley** [comment]
Code should make it to the master eventually anyway; as long as I am adding a new notebook and not working on code others may be working on then no problem I think to push from my master.

**Comment by twhyntie** [comment]
LGTM - enjoying the **Panda** stuff :smile:

@Tontonis?

**Comment by RaoOfPhysics** [comment]
@twhyntie: If one of you has vetted the PR, I think it's fine to merge. I tagged both in case one was busy. :)

**Comment by tpmccauley** [comment]
Thanks all. Now is the last of my pushes to master :)

**Pull request merged**
